function STRUCT=distrStruct(nrIndvs)

STRUCT=struct('Eps',[],'matrix',[],'startpoint',[],'minEps',[],'histogram',[],'survival_histogram',[],'okindex',[], ...
    'sumEps',NaN(1,nrIndvs), ...
     'nrEps',NaN(1,nrIndvs), ...
   'meanEps',NaN(1,nrIndvs), ...
         'F',NaN(1,nrIndvs), ...
         'B',NaN(1,nrIndvs), ...
        'wB',struct('k',NaN(1,nrIndvs),'lambda',NaN(1,nrIndvs),'rsquare',NaN(3,nrIndvs),'okfit',[]), ...
       'wnl',struct('k',NaN(1,nrIndvs),'lambda',NaN(1,nrIndvs),'rsquare',NaN(3,nrIndvs),'okfit',[],'counter',NaN(1,nrIndvs)), ...
      'wlin',struct('k',NaN(1,nrIndvs),'lambda',NaN(1,nrIndvs),'rsquare',NaN(3,nrIndvs),'okfit',[]), ...
         'M',NaN(1,nrIndvs), ...
         'DFA',NaN(1,nrIndvs), ...
         'weibull_pdf',@(x,k,lambda)((repmat(k./lambda,[size(x,1) 1]).*(x*(1./lambda)).^repmat(k-1,[size(x,1) 1])).*exp(-(x*(1./lambda)).^repmat(k,[size(x,1),1]))), ...
         'weibull_survival',@(x,k,lambda)(-(x*(1./lambda)).^repmat(k,[size(x,1) 1])), ...
         'weibull_lin',@(x,k,lambda)(x*k-repmat(k.*log(lambda),[size(x,1) 1])) ...
         );
STRUCT.Eps=cell(1,nrIndvs);
end